stages:
  train:
    cmd: python scripts/train.py --data_path data --epochs 1
    deps:
      - scripts/train.py
      - TR_ADE.py
      - TR_ADE_pipeline.py
      - subclasses.py
      - subnetworks.py
      - utils.py
      - configs/train.yaml
      - data/heart.csv     # tracked by Git
    outs:
      - artifacts/model/   # model output folder (DVC will manage this)
      - artifacts/metrics.json
