name: ci

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  smoke:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install pip-tools and compile lock
        run: |
          python -m pip install --upgrade pip
          pip install pip-tools
          pip-compile requirements.in -o requirements.txt
          cat requirements.txt

      - name: Install from generated lock
        run: pip install -r requirements.txt

      - name: Ensure PYTHONPATH includes repo root
        run: echo "PYTHONPATH=$PWD" >> $GITHUB_ENV

      - name: Prepare tiny dataset
        run: |
          python - <<'PY'
          import pathlib as p, pandas as pd
          d = p.Path('data'); d.mkdir(exist_ok=True)
          f = d/'heart.csv'
          if not f.exists():
              pd.DataFrame({
                  "Age":[50,60,70,55],
                  "Sex":[1,0,1,0],
                  "ExerciseAngina":[0,1,0,1],
                  "HeartDisease":[1,0,1,0],
              }).to_csv(f, index=False)
          print("Data ready:", f.resolve())
          PY

      - name: Run tests
        run: pytest -q

      - name: Smoke train (1 epoch)
        run: |
          python scripts/train.py --data_path data --epochs 1
